services:
    mariadb:
        build: ./services/mariadb
        image: mariadb
        container_name: mariadb
        volumes:
          - mdb_data:/var/lib/mysql
        env_file: .env
        networks:
          - inception
        restart: always
    wordpress:
        build: ./services/wordpress
        image: wordpress
        container_name: wordpress
        volumes:
          - wp_data:/var/www/html
        env_file: .env
        depends_on:
          - mariadb
        networks:
          - inception
        restart: always
    nginx:
        build: ./services/nginx
        image: nginx
        container_name: nginx
        volumes:
          - wp_data:/var/www/html
        depends_on:
          - wordpress
        ports:
          - 443:443
        networks:
          - inception
        restart: always
    nginx-exporter:
        container_name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.3.0
        command:
          - "--nginx.scrape-uri=http://nginx:8080/stub_status"
        networks:
          - inception
        depends_on:
          - nginx 
    mariadb-exporter:
        container_name: mariadb-exporter
        image: prom/mysqld-exporter:main
        env_file: .env
        volumes:
          - "./services/prometheus/mariadb:/home"
        networks:
          - inception
        depends_on:
          - mariadb
        entrypoint: ["sh", "/home/init.sh"]
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
          - 9090:9090
        volumes:
          - "./services/prometheus:/config"
        networks:
          - inception
        restart: always
        command:
          - "--config.file=/config/prometheus.yml"
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        env_file: .env
        ports:
          - 3000:3000
        networks:
          - inception
        volumes:
          - "./services/grafana/admin_pass:/etc/secrets/admin_pass"
          - "./services/grafana/default_home_dashboard_path:/etc/config/default_home_dashboard_path"
          - "./services/grafana/dashboards/providers:/etc/grafana/provisioning/dashboards"
          - "./services/grafana/dashboards/files:/var/lib/grafana/dashboards"
          - "./services/grafana/datasources:/etc/grafana/provisioning/datasources"
        restart: always

volumes:
    mdb_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "./data/mariadb"
    wp_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "./data/wordpress"

networks:
    inception:
      driver: bridge
