services:
    mariadb:
        build: ./services/mariadb
        image: mariadb
        container_name: mariadb
        volumes:
          - mdb_data:/var/lib/mysql
        env_file: .env
        networks:
          - inception
        restart: always
    wordpress:
        build: ./services/wordpress
        image: wordpress
        container_name: wordpress
        volumes:
          - wp_data:/var/www/html
        env_file: .env
        depends_on:
          - mariadb
        networks:
          - inception
        restart: always
    nginx:
        build: ./services/nginx
        image: nginx
        container_name: nginx
        volumes:
          - wp_data:/var/www/html
        depends_on:
          - wordpress
        ports:
          - 443:443
        networks:
          - inception
        restart: always

volumes:
    mdb_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "${PWD}/data/mariadb"
    wp_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "${PWD}/data/wordpress"

networks:
    inception:
      driver: bridge
